[ ] const wDynamicMainWindow = Калькулятор
[ ] 
[-] window MainWin Калькулятор
	[ ] locator "/MainWin[@caption='Калькулятор']"
	[ ] 
	[ ] // The working directory of the application when it is invoked
	[ ] const sDir = "C:\WINDOWS\system32"
	[ ] 
	[ ] // The command line used to invoke the application
	[ ] const sCmdLine = "C:\WINDOWS\system32\calc.exe"
	[ ] 
	[ ] // The list of windows the recovery system is to leave open
	[ ] // const lwLeaveOpenWindows = {?}
	[ ] // const lsLeaveOpenLocators = {?}
[ ] 
[ ] 
